[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/docker-init.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
ADMIN_PASSWORD = "${ADMIN_PASSWORD}"
SECRET_KEY = "${SECRET_KEY}"
